
import Metodos_sql.Metodos_sql;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author brend
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }
    Metodos_sql metod =new Metodos_sql();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lusername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lpassword = new javax.swing.JPasswordField();
        btn_iniciar = new javax.swing.JButton();
        btn_r = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user4.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user4.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, -1, -1));

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Username:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        lusername.setBackground(new java.awt.Color(0, 102, 153));
        lusername.setForeground(new java.awt.Color(255, 255, 255));
        lusername.setCaretColor(new java.awt.Color(255, 255, 255));
        lusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lusernameActionPerformed(evt);
            }
        });
        jPanel1.add(lusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 420, 30));

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        lpassword.setBackground(new java.awt.Color(0, 102, 153));
        lpassword.setForeground(new java.awt.Color(255, 255, 255));
        lpassword.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(lpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 420, 30));

        btn_iniciar.setBackground(new java.awt.Color(121, 182, 255));
        btn_iniciar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_iniciar.setText("Iniciar sesion");
        btn_iniciar.setBorder(null);
        btn_iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_iniciarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 130, 40));

        btn_r.setBackground(new java.awt.Color(0, 153, 153));
        btn_r.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_r.setText("Registrarse");
        btn_r.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rActionPerformed(evt);
            }
        });
        jPanel1.add(btn_r, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 130, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("o");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_rActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rActionPerformed
       registro v= new registro();
       v.setVisible(true);
       this.dispose();
        
    }//GEN-LAST:event_btn_rActionPerformed

    private void btn_iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_iniciarActionPerformed
      String busqueda_usuario= metod.buscarusuarioRegistrado(lusername.getText(),lpassword.getText());
       if(lusername.getText().equals("root") && lpassword.getText().equals("root")){
           JOptionPane.showMessageDialog(this,"Bienvenido Administrador");
            Personalizacion p= new Personalizacion();
           p.setVisible(true);
           this.dispose();
       }else if(busqueda_usuario.equals("usuario encontrado")){
           String busqueda_nombre=metod.buscarNombre(lusername.getText());
           JOptionPane.showMessageDialog(this,"Bienvenid@ \n " +busqueda_nombre);
           Personalizacion p= new Personalizacion();
           p.setVisible(true);
           this.dispose();
       }else{
           JOptionPane.showMessageDialog(this,"Usuario y/o contraseña incorrectos");
           lusername.setText("");
           lpassword.setText("");
       }
    }//GEN-LAST:event_btn_iniciarActionPerformed

    private void lusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lusernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_iniciar;
    private javax.swing.JButton btn_r;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField lpassword;
    private javax.swing.JTextField lusername;
    // End of variables declaration//GEN-END:variables
}
